In [2]:
import numpy

In [3]:
a = numpy.array([10, 20, 30, 40])

array([10, 20, 30, 40])

In [6]:
mat = numpy.array([[10, 20, 30], [40, 50, 60]])
mat

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
print(mat[1,2])

60


In [9]:
mat[1:]  #linha

array([[40, 50, 60]])

In [12]:
mat[:,0] #coluna

array([10, 40])

In [13]:
mat.transpose() #transposta

array([[10, 40],
       [20, 50],
       [30, 60]])

In [16]:
m1 = numpy.array([[10, 15], [20, 30]])
m2 = numpy.array([[20, 25], [30, 35]])

In [19]:
m3 = m1 + m2

In [20]:
m3

array([[30, 40],
       [50, 65]])

In [21]:
m3.argmax() # indice do maior numero no array

3

In [22]:
m3.argmin() # indice do menor

0

In [24]:
#consideracoes: o numpy array tem vantagem em relacao as listas do python pois sao mais compactas>
#Consomem menos, pode n ter diferenca para pequenas coisas, mas para grandes qntidades sim.

In [25]:
#m3.mean() -> media da matriz
#m3.diagonal() -> diagonal da matriz
#m3.ndim() -> dimensão